@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Skip Checkout Page - Redirect Payment Channel

participant "Browser/App" as browser
participant merchant as "Merchant"
participant vue as "Hosted Checkout"
participant airtime as "Airtime"
participant airbag as "Airbag"
participant raison as "Raison"
participant gateway as "Gateway"
participant fraud as "Fraud Service"
participant provider as "Provider"

== Initialization Phase ==

merchant -> airtime: POST /Payment/init

group #F2F2F2 EPCInitTxn (initializeTransaction)
    airtime -> airbag: EPCInitTxn.init()

    note over airbag: GATE CHECK => Feature Flag for Supplier(Merchant) & PC Eligibility

    alt #E8F5E9 CASE1: Feature Flag: Enabled & PC: Eligible
         group **SYNC FLOW**: InitializeHC
                   note over airbag, provider: Now waiting for immediate Provider response end
                   airbag -> raison : CreatePayment
                   group **PreCreatePaymentValidation**
                   airbag -> airbag: Check\n1. MNOActivation\n2.PreCreatePaymentStatus\n3.AmountLimitCheck
                        alt GATE CHECK => Feature Flag for Supplier(Merchant) & PC Eligibility
                        airbag -[#red]> fraud: <b>processing Fraud Risk Check</b>
                        fraud --[#red]>airbag: 200 OK: ResultCode=SUCCESS
                        airbag -[#red]> airbag: profileMap["fraudCheckedBeforePaymentInit]=true
                        end alt
                   raison -> provider : Payment Gateway Init
                   provider --> raison : 200 OK (redirectUrl)
                   raison -> airbag: txnStatus: WaitToConfirm
                   end group
         end

airbag --> airtime: { REDIRECT_ENABLED: true, REDIRECT_URL: provider_url }
        airtime -> merchant: 200 OK
        note right
            <initResult>
                <redirectUrl>https://provider.com/pay</redirectUrl>
                <resultCode>0</resultCode>
                <txnId>7712376985402148501</txnId>
            </initResult>
        end note
    else #FEF9E7 CASE2: Feature Flag: Enabled & PC: NOT Eligible
        group **ASYNC FLOW**: InitializeHC
            airbag -> raison : CreatePayment
                       raison -> provider : Payment Gateway Init
                       provider --> raison : 200 OK (redirectUrl)
                       raison -> airbag: txnStatus: WaitToConfirm
        end
        airbag --> airtime: { REDIRECT_ENABLED: true, REDIRECT_URL: airtime_url }
        airtime -> merchant: 200 OK
        note right
            <initResult>
                <redirectUrl>https://airtime-sgp.codapayments.com/airtime/begin?txn_id=123</redirectUrl>
                <resultCode>0</resultCode>
                <txnId>7712376985402148501</txnId>
            </initResult>
        end note

    else #FEF9E7 CASE3 Feature Flag: DISABLED
        group **ASYNC FLOW**: InitializeHC
             airbag -> raison : CreatePayment
                        raison -> provider : Payment Gateway Init
                        provider --> raison : 200 OK (redirectUrl)
                        raison -> airbag: txnStatus: WaitToConfirm
        end
        airbag --> airtime: { REDIRECT_ENABLED: false }
        airtime -> merchant: 200 OK
        note right
            <initResult>
                <resultCode>0</resultCode>
                <txnId>7712376985402148501</txnId>
            </initResult>
        end note
    end
end

== User Payment Process ==

merchant -> browser: Redirect User to redirectUrl (Provider OR Airtime)
alt Redirected to Airtime ( CODA's Hosted Payment Page)
    browser -> airtime: <b>https://airtime-sgp.codapayments.com/airtime/begin?txn_id=1234</b>
    airtime -> browser: HTTP 302: Redirect to Vue3 <b>[https://airtime-sgp.codapayments.com/airtime/web-app/begin?txn_id=123]</b>
    airtime -> airbag: Checkout Manager
    note over airbag,fraud: Fraud Risk Check on Checkout Page
    airbag -> fraud: processing Fraud Risk Check
    airbag <-- fraud: 200 OK: ResultCode=SUCCESS
    airbag -> airtime: Txn: ResultCode=431
    airtime -> browser: Coda's Hosted Payment Page Landed
    browser -> provider: User clicks "Continue" and goes to Provider (https://provider.com/pay)
else #E8F5E9 Redirected to Provider
    browser -> provider: https://provider.com/pay
end
 provider --> browser: Confirm Payments etc

== Return & Notification Flow ==

group #E8F5E9 Return to Coda
    provider -> browser: Redirect to Coda's return_url
    browser -> airtime: GET /airtime/jpn/paypay/return?txnid=7712376985402148501
    airtime -> vue: Redirect to /airtime/web-app/begin?txn_id=...
    vue -> browser: Render Result Page (Payment Successful OR Failed )
end

group #FFECB3 Async Backend Notification
    provider -> gateway: Callback/Webhook Notification
    gateway -> airbag: EPCConfirm
    airbag -> merchant: Send Notification Callback (HTTP POST)
end

@enduml